### ISSUE TITLE
I failed. :)

### ISSUE THREAD

**Issue by antplus** [imchlorine/PTVTimetable#1]
I've been tinkering with it, your sample code worked great.  I tried
Mount Waverley Railway Station and Mount Waverley Station, same variations for Flinders but still getting errors.  I took the name from the PTV app.  Thanks for the great script, will be awesome to get it working.

to customize your PTV timetable. 
const routeType = "0"
const routeName = "Glen Waverley Line"
const fromStop = "Mount Waverley Railway Station"
const toStop = "Flinders Street Railway Station"

2022-12-10 21:18:58: Error on line 284:21: TypeError: undefined is not an object (evaluating 'stops.find')

**Comment by antplus** [comment]
Code around line 284

[routeType]
    }
    let stop = stops.find(stop => stop.label === stopName)
    if (stop === undefined)
        stop = stops[0]
    return stop
}

**Comment by imchlorine** [comment]
Hi, if you are using `routeType = "0"` means `train`, so your `routeName` should be `Glen Waverley`, and your stop name should not contains "Railway" as Railway Station is for V/Line `routeType = "3"`. BTW, I don't think `Mount Waverley Station` is a `Railway Station` , I can not find it on the PTV app. Because PTV API does not support fuzzy search, so your stop name should be the same as on the PTV app or website. 

So the correct code should be
```
const routeType = "0"
const routeName = "Glen Waverley"
const fromStop = "Mount Waverley Station"
const toStop = "Flinders Street Station"
```
Hope this can help.

**Comment by antplus** [comment]
You're a legend, all sorted.  Glad to see someone's Saturday night is as interesting as mine.  😃 

Thanks for the prompt help!

**Comment by imchlorine** [comment]
You're welcome. Recommend to anyone who needs, spread the love
